site_name: State of Ranswood Legislation
site_url: https://github.io/WarpedEntrance/legislation/
site_author: WarpedEntrance
site_description: Active legislation for the State of Ranswood Roblox group
repo_name: WarpedEntrance/legislation
repo_url: https://warpedentrance.github.io/legislation/

theme:
  name: material
  features:
    - tabs

  logo: assets/logo.png
  favicon: assets/favicon.ico

  icon:
    repo: fontawesome/brands/github

  include_search_page: false
  search_index_only: true

  language: en

plugins:
  - search:
      separator: '[\s\-]+'
  - awesome-pages
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html

extra_css:
- stylesheets/extra.css
